Repository zyon-project/zyon-doc, pull requests merged in 2022-10, with the labels that each got.

#5 feat(index): update home page to show coming soon page
  .gitbook/assets/css/style.css
  .gitbook/assets/fonts/Empires.otf
  .gitbook/assets/js/index.js
  index.html
Labels: feature

#6 Uploaded Logo
  .hacktoberfest/proposals/logo/Omm2005/1.png
  .hacktoberfest/proposals/logo/Omm2005/2.png
Labels: feature, hacktoberfest

#7 :octocat: GitHub Settings
  .gitbook/assets/css/style.css
  .gitbook/assets/fonts/Empires.otf
  .gitbook/assets/js/index.js
  .github/CODE_OF_CONDUCT.md
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/ISSUE_TEMPLATE/🚀-feature-request.md
  .github/ISSUE_TEMPLATE/🪲-bug-report.md
  .github/PULL_REQUEST_TEMPLATE.md
  index.html
Labels: documentation, feature
